// components/RootLayout.js

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/SideBar";
import { Inter } from "next/font/google";
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import "../styles/output.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = useRouter();

  useEffect(() => {
    // Get the current language from the router locale
    const lang = router.locale;

    // Set dynamic favicon based on the language
    const faviconLink = document.querySelector("link[rel*='icon']");
    faviconLink.href = `/favicon-${lang}.ico`;
  }, [router.locale]); // Run whenever the locale changes

  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className="dark:bg-body bg-white font-[Sora] dark:text-white text-dark">
        <Navbar />
        <main>
          <div className="container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">
            <SideBar />
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </>
  );
}
