import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/SideBar";
import { Inter } from "next/font/google";
import "../styles/output.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Get the current language from the HTML lang attribute
  const lang = document.documentElement.lang;

  return (
    <html lang="en">
      <Head>
        {/* Set dynamic favicon based on the language */}
        <link rel="icon" href={`/favicon-${lang}.ico`} />
      </Head>
      <body className="dark:bg-body bg-white font-[Sora] dark:text-white text-dark">
        <Navbar />
        <main>
          <div className="container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">
            <SideBar />
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html >
  );
}
