import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-body bg-white font-[Sora] dark:text-white text-dark">
        <Navbar />
        <main>
          <div class="container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">



            <div class="content">
              <div class="grid sm:grid-cols-2 xl:grid-cols-3 gap-7">







              </div>
            </div>
          </div>
        </main>
        <Footer />
      </body>
    </html >
  );
}
